// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdFN1FZWvAkeVWjqmaY_1D5zkrh4XsN0s',
    appId: '1:877900563269:web:500d962d62b493bc40342c',
    messagingSenderId: '877900563269',
    projectId: 'prakflutterfirebase-1e2c4',
    authDomain: 'prakflutterfirebase-1e2c4.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-1e2c4.appspot.com',
    measurementId: 'G-5VRDS6P2M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmVbfq37y3rOzyaMo-wdyDjaJrb7zrKDI',
    appId: '1:877900563269:android:83137f3ebd99886a40342c',
    messagingSenderId: '877900563269',
    projectId: 'prakflutterfirebase-1e2c4',
    storageBucket: 'prakflutterfirebase-1e2c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPT9GjT5rFs8ZrDOEMa-fLfae9YEfHhcQ',
    appId: '1:877900563269:ios:80346e9e75faf0a640342c',
    messagingSenderId: '877900563269',
    projectId: 'prakflutterfirebase-1e2c4',
    storageBucket: 'prakflutterfirebase-1e2c4.appspot.com',
    iosBundleId: 'com.example.praktikum09',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPT9GjT5rFs8ZrDOEMa-fLfae9YEfHhcQ',
    appId: '1:877900563269:ios:80346e9e75faf0a640342c',
    messagingSenderId: '877900563269',
    projectId: 'prakflutterfirebase-1e2c4',
    storageBucket: 'prakflutterfirebase-1e2c4.appspot.com',
    iosBundleId: 'com.example.praktikum09',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdFN1FZWvAkeVWjqmaY_1D5zkrh4XsN0s',
    appId: '1:877900563269:web:2c29daa21ba8fefd40342c',
    messagingSenderId: '877900563269',
    projectId: 'prakflutterfirebase-1e2c4',
    authDomain: 'prakflutterfirebase-1e2c4.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-1e2c4.appspot.com',
    measurementId: 'G-44P8QQT6P1',
  );
}
